version: '3'
services:
  mongodb:
    image: mongo
    container_name: rules-engine-db
    environment:
      - MONGODB_URI=${MONGODB_URI}
  
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_NAME=${MONGODB_NAME}
    ports:
      - ${PORT}:9000
    container_name: server-rules-engine